## 1. Import the dataset

In [1]:
import pandas as pd

df = pd.read_csv("trends.csv")
print("Dataset loaded successfully.")
display(df.head())

Dataset loaded successfully.

  location  year         category  rank  query
0   Global  2001  Consumer Brands     1  Nokia
1   Global  2001  Consumer Brands     2   Sony
2   Global  2001  Consumer Brands     3    BMW
3   Global  2001  Consumer Brands     4   Palm
4   Global  2001  Consumer Brands     5  Adobe

## 2. Identify and handle missing values

In [2]:
print("Missing values:")
print(df.isnull().sum())

# Handle missing values
df = df.dropna()

print("Missing values handled.")

Missing values:
location    0
year        0
category    0
rank        0
query       0
dtype: int64
Missing values handled.

## 3. Remove duplicate records

In [3]:
print("Duplicates before:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates after:", df.duplicated().sum())

Duplicates before: 10
Duplicates after: 0

## 4. Correct inconsistent entries

In [10]:
# Correct inconsistent text entries

for col in df.select_dtypes(include=["object", "string"]).columns:
    df[col] = df[col].astype("string").str.strip().str.lower()

print("Inconsistent entries corrected.")

Inconsistent entries corrected.

## 5. Assign appropriate data types

In [5]:
# Convert numeric columns
df["year"] = pd.to_numeric(df["year"])
df["rank"] = pd.to_numeric(df["rank"])

print(df.dtypes)

location      str
year        int64
category      str
rank        int64
query         str
dtype: object

## 6. Rename columns where necessary

In [6]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

print("Column names:")
print(df.columns.tolist())

Column names:
['location', 'year', 'category', 'rank', 'query']

## 7. Check and correct formatting issues

In [11]:


for col in df.select_dtypes(include=["object", "string"]).columns:
    df[col] = df[col].astype("string").str.strip()

print("Formatting checked and corrected.")

Formatting checked and corrected.

## 8. Verify the final cleaned dataset

In [8]:
print("Final shape:", df.shape)
print("Missing values:", df.isnull().sum().sum())
print("Duplicate records:", df.duplicated().sum())
print("\nData types:")
print(df.dtypes)

display(df.head())

Final shape: (26945, 5)
Missing values: 0
Duplicate records: 0

Data types:
location      str
year        int64
category      str
rank        int64
query         str
dtype: object

  location  year         category  rank  query
0   Global  2001  Consumer Brands     1  Nokia
1   Global  2001  Consumer Brands     2   Sony
2   Global  2001  Consumer Brands     3    BMW
3   Global  2001  Consumer Brands     4   Palm
4   Global  2001  Consumer Brands     5  Adobe

## Save the cleaned dataset

In [9]:
df.to_csv("trends_cleaned.csv", index=False)
print("Cleaned dataset saved as trends_cleaned.csv")

Cleaned dataset saved as trends_cleaned.csv

## Cleaning Summary

1. Dataset imported successfully.
2. Missing values checked and handled.
3. Duplicate records removed.
4. Inconsistent spaces corrected.
5. Data types corrected.
6. Column names standardized.
7. Formatting checked.
8. Final dataset verified and saved.