# Initial Data Analysis – trends.csv

In [1]:
import paDndas as pd

df = pd.read_csv("trends.csv")
print("Dataset loaded successfully.")

Dataset loaded successfully.

In [2]:
print(df.head())

  location  year         category  rank  query
0   Global  2001  Consumer Brands     1  Nokia
1   Global  2001  Consumer Brands     2   Sony
2   Global  2001  Consumer Brands     3    BMW
3   Global  2001  Consumer Brands     4   Palm
4   Global  2001  Consumer Brands     5  Adobe

In [3]:
print(df.tail())

      location  year category  rank                query
26950  Vietnam  2020   Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020   Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020   Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020   Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020   Là Gì?     5       Đông Lào là gì

In [4]:
print("Shape:", df.shape)
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Shape: (26955, 5)
Rows: 26955
Columns: 5

In [5]:
print(df.columns.tolist())

['location', 'year', 'category', 'rank', 'query']

In [6]:
print(df.dtypes)

location      str
year        int64
category      str
rank        int64
query         str
dtype: object

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26955 entries, 0 to 26954
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   location  26955 non-null  str
 1   year      26955 non-null  int64
 2   category  26955 non-null  str
 3   rank      26955 non-null  int64
 4   query     26955 non-null  str
dtypes: int64(2), str(3)
memory usage: 1.0 MB

In [16]:
df.describe()

               year         rank
count  26955.000000  26955.00000
mean    2015.243369      3.00000
std        3.564683      1.41424
min     2001.000000      1.00000
25%     2013.000000      2.00000
50%     2016.000000      3.00000
75%     2018.000000      4.00000
max     2020.000000      5.00000

In [9]:
print(df.describe(include="all").T)

            count unique            top  freq         mean       std     min  \
location    26955     83  United States  2070          NaN       NaN     NaN
year      26955.0    NaN            NaN   NaN  2015.243369  3.564683  2001.0
category    26955   2450         People   760          NaN       NaN     NaN
rank      26955.0    NaN            NaN   NaN          3.0   1.41424     1.0
query       26955  18431    Paul Walker    84          NaN       NaN     NaN

             25%     50%     75%     max
location     NaN     NaN     NaN     NaN
year      2013.0  2016.0  2018.0  2020.0
category     NaN     NaN     NaN     NaN
rank         2.0     3.0     4.0     5.0
query        NaN     NaN     NaN     NaN

In [10]:
missing = df.isnull().sum()
print(missing)
print("Total missing values:", missing.sum())

location    0
year        0
category    0
rank        0
query       0
dtype: int64
Total missing values: 0

In [18]:
duplicates = df.duplicated().sum()
print("Duplicate rows:", duplicates)

Duplicate rows: 10

In [12]:
print(df.nunique())

location       83
year           20
category     2450
rank            5
query       18431
dtype: int64

In [19]:
df.drop_duplicates()

      location  year         category  rank                query
0       Global  2001  Consumer Brands     1                Nokia
1       Global  2001  Consumer Brands     2                 Sony
2       Global  2001  Consumer Brands     3                  BMW
3       Global  2001  Consumer Brands     4                 Palm
4       Global  2001  Consumer Brands     5                Adobe
...        ...   ...              ...   ...                  ...
26950  Vietnam  2020           Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020           Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020           Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020           Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020           Là Gì?     5       Đông Lào là gì

[26945 rows x 5 columns]

In [13]:
for col in df.columns:
    print(f"\n{col}: {df[col].nunique()} unique values")
    print(df[col].dropna().unique()[:10])

location: 83 unique values
<StringArray>
[        'Global',         'France',        'Germany', 'United Kingdom',
      'Australia',         'Canada',          'Italy',    'Netherlands',
          'Spain',  'United States']
Length: 10, dtype: str

year: 20 unique values
[2001 2002 2003 2004 2005 2006 2007 2008 2009 2010]

category: 2450 unique values
<StringArray>
[   'Consumer Brands',                'Men',             'Movies',
 'MP3 Music Services',       'Music Groups',       'New Products',
     'News Resources',          'Retailers',             'Sports',
           'TV Shows']
Length: 10, dtype: str

rank: 5 unique values
[1 2 3 4 5]

query: 18431 unique values
<StringArray>
[          'Nokia',            'Sony',             'BMW',            'Palm',
           'Adobe',     'Nostradamus', 'Osama bin Laden',          'Eminem',
 'Michael Jackson',    'Howard Stern']
Length: 10, dtype: str

In [14]:
numeric_cols = df.select_dtypes(include="number").columns
print("Numerical columns:", list(numeric_cols))
print("\nMean:")
print(df[numeric_cols].mean())
print("\nMedian:")
print(df[numeric_cols].median())
print("\nMinimum:")
print(df[numeric_cols].min())
print("\nMaximum:")
print(df[numeric_cols].max())
print("\nStandard deviation:")
print(df[numeric_cols].std())

Numerical columns: ['year', 'rank']

Mean:
year    2015.243369
rank       3.000000
dtype: float64

Median:
year    2016.0
rank       3.0
dtype: float64

Minimum:
year    2001
rank       1
dtype: int64

Maximum:
year    2020
rank       5
dtype: int64

Standard deviation:
year    3.564683
rank    1.414240
dtype: float64

In [15]:
print("Missing values by column:")
print(df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())
print("\nData types:")
print(df.dtypes)

Missing values by column:
location    0
year        0
category    0
rank        0
query       0
dtype: int64

Duplicate rows: 10

Data types:
location      str
year        int64
category      str
rank        int64
query         str
dtype: object

In [1]:
df = df.drop_duplicates()

print("Duplicate rows removed successfully.")
print("Remaining duplicate rows:", df.duplicated().sum())
print("New shape:", df.shape)

NameError: name 'df' is not defined