In [2]:
import pandas as pd

df = pd.read_csv("trends.csv")

print("Dataset loaded successfully.")
print("Shape:", df.shape)
df.head()

Dataset loaded successfully.
Shape: (26955, 5)

  location  year         category  rank  query
0   Global  2001  Consumer Brands     1  Nokia
1   Global  2001  Consumer Brands     2   Sony
2   Global  2001  Consumer Brands     3    BMW
3   Global  2001  Consumer Brands     4   Palm
4   Global  2001  Consumer Brands     5  Adobe

In [3]:

print("Dataset Information:")
df.info()

print("\nDataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nFirst 5 Records:")
display(df.head())

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 26955 entries, 0 to 26954
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   location  26955 non-null  str
 1   year      26955 non-null  int64
 2   category  26955 non-null  str
 3   rank      26955 non-null  int64
 4   query     26955 non-null  str
dtypes: int64(2), str(3)
memory usage: 1.0 MB

Dataset Shape: (26955, 5)

Column Names:
['location', 'year', 'category', 'rank', 'query']

First 5 Records:

  location  year         category  rank  query
0   Global  2001  Consumer Brands     1  Nokia
1   Global  2001  Consumer Brands     2   Sony
2   Global  2001  Consumer Brands     3    BMW
3   Global  2001  Consumer Brands     4   Palm
4   Global  2001  Consumer Brands     5  Adobe

In [4]:

print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
location    0
year        0
category    0
rank        0
query       0
dtype: int64

In [5]:

missing_percentage = (df.isnull().sum() / len(df)) * 100

print("Missing value percentage:")
print(missing_percentage)

Missing value percentage:
location    0.0
year        0.0
category    0.0
rank        0.0
query       0.0
dtype: float64

In [7]:

print("Number of duplicate records:", df.duplicated().sum())


df = df.drop_duplicates()

print("Duplicates removed successfully.")
print("New shape:", df.shape)

Number of duplicate records: 10
Duplicates removed successfully.
New shape: (26945, 5)

In [8]:

for column in df.select_dtypes(include=['object']).columns:
    print("\nColumn:", column)
    print(df[column].unique()[:20])

Column: location
<StringArray>
[        'Global',         'France',        'Germany', 'United Kingdom',
      'Australia',         'Canada',          'Italy',    'Netherlands',
          'Spain',  'United States',      'Argentina',        'Austria',
        'Belgium',         'Brazil',          'Chile',          'China',
       'Colombia',        'Czechia',        'Denmark',        'Finland']
Length: 20, dtype: str

Column: category
<StringArray>
[    'Consumer Brands',                 'Men',              'Movies',
  'MP3 Music Services',        'Music Groups',        'New Products',
      'News Resources',           'Retailers',              'Sports',
            'TV Shows',         'Video Games',               'Women',
            'Athletes',        'Kids' Images', 'Musicians and Bands',
        'News Stories',          'Technology', 'Travel Destinations',
             'Marques',       'Personnalités']
Length: 20, dtype: str

Column: query
<StringArray>
[            'Nokia',              'Sony',               'BMW',
              'Palm',             'Adobe',       'Nostradamus',
   'Osama bin Laden',            'Eminem',   'Michael Jackson',
      'Howard Stern',      'Harry Potter', 'Lord of the Rings',
     'Final Fantasy',       'Tomb Raider',             'Shrek',
          'Morpheus',           'Napster',          'Gnutella',
             'Kazaa',       'Audiogalaxy']
Length: 20, dtype: str

C:\Users\shiva\AppData\Local\Temp\ipykernel_28056\3079136940.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in df.select_dtypes(include=['object']).columns:

In [10]:
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip()

print("Inconsistent spaces removed.")

Inconsistent spaces removed.

C:\Users\shiva\AppData\Local\Temp\ipykernel_28056\185135763.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [11]:
df["location"] = df["location"].astype("string")
df["year"] = df["year"].astype("int64")
df["category"] = df["category"].astype("string")
df["rank"] = df["rank"].astype("int64")
df["query"] = df["query"].astype("string")

print(df.dtypes)

location    string
year         int64
category    string
rank         int64
query       string
dtype: object

In [12]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

print("Columns:", df.columns.tolist())

Columns: ['location', 'year', 'category', 'rank', 'query']

In [13]:
for col in df.select_dtypes(include="string").columns:
    df[col] = df[col].str.strip()

print("Formatting checked and corrected.")

Formatting checked and corrected.

In [14]:
print("Final Shape:", df.shape)
print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

print("\nFinal Dataset:")
display(df.head())

Final Shape: (26945, 5)

Missing Values:
location    0
year        0
category    0
rank        0
query       0
dtype: int64

Duplicate Rows: 0

Data Types:
location    string
year         int64
category    string
rank         int64
query       string
dtype: object

Final Dataset:

  location  year         category  rank  query
0   Global  2001  Consumer Brands     1  Nokia
1   Global  2001  Consumer Brands     2   Sony
2   Global  2001  Consumer Brands     3    BMW
3   Global  2001  Consumer Brands     4   Palm
4   Global  2001  Consumer Brands     5  Adobe

In [15]:
df.to_csv("trends_cleaned.csv", index=False)
print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.